name: DAST Scan
on:
  workflow_call:
    inputs:
      target_url:
        required: true
        type: string

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP ZAP Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: ${{ inputs.target_url }}
          fail_action: false # Set to true to block builds on security flaws
