name: Email Notifications
on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      message:
        required: true
        type: string
    secrets:
      mail_username:
        required: true
      mail_password:
        required: true

jobs:
  email-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Mail
        uses: dawidd6/action-send-mail@v3
        continue-on-error: true
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.mail_username }}
          password: ${{ secrets.mail_password }}
          subject: "SkillPulse Deployment [${{ inputs.status }}]"
          to: knhapndt@gmail.com
          from: "SkillPulse DevSecOps <${{ secrets.mail_username }}>"
          body: |
            Deployment Status: ${{ inputs.status }}
            
            Message: ${{ inputs.message }}
            
            Commit: ${{ github.sha }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            
            Check details here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
