name: Automated Lifecycle Backups
on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  workflow_dispatch: # Manual trigger

jobs:
  backup:
    name: Production Data Protection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Setup Kubectl
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }} # Encoded kubeconfig secret

      - name: Run Backup Script
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          chmod +x ./scripts/backup.sh
          ./scripts/backup.sh
